### ISSUE TITLE
cannot run inside of a docker compose

### ISSUE THREAD

**Issue by alberttwong** [data-catering/duckdb-docker#5]
it just quits.

**Comment by pflooky** [comment]
Hey @alberttwong !

Thanks for raising the issue.
To help run it in docker-compose, you can add the following entrypoint to keep the container running:

```
services:
  duckdb:
    image: datacatering/duckdb:v1.0.0
    entrypoint: tail -F anything
```
